<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F3186QF" failures="4" tests="10" name="Test" time="187.377" errors="0" timestamp="2019-09-18T20:44:33 ART">
  <testcase classname="test.TestAutomation" name="ControlMail" time="14.274"/>
  <testcase classname="test.TestAutomation" name="Login_Correcto" time="4.796">
    <failure type="java.lang.AssertionError" message="BRMS KTkIL expected:&amp;lt;BRMS KTkIL&amp;gt; but was:&amp;lt;Error en caso de datos incorrectos!&amp;gt;">
      <![CDATA[java.lang.AssertionError: BRMS KTkIL expected:<BRMS KTkIL> but was:<Error en caso de datos incorrectos!>
at test.TestAutomation.Login_Correcto(TestAutomation.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login_Correcto -->
  <testcase classname="test.TestAutomation" name="Login_Correcto" time="6.795">
    <failure type="java.lang.AssertionError" message="nUjk FtrEX expected:&amp;lt;Sign in&amp;gt; but was:&amp;lt;Error en caso de datos incorrectos!&amp;gt;">
      <![CDATA[java.lang.AssertionError: nUjk FtrEX expected:<Sign in> but was:<Error en caso de datos incorrectos!>
at test.TestAutomation.Login_Correcto(TestAutomation.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login_Correcto -->
  <testcase classname="test.TestAutomation" name="Login_Correcto" time="4.223">
    <failure type="java.lang.AssertionError" message="FbtB ipqeP expected:&amp;lt;FbtB ipqeP&amp;gt; but was:&amp;lt;Error en caso de datos incorrectos!&amp;gt;">
      <![CDATA[java.lang.AssertionError: FbtB ipqeP expected:<FbtB ipqeP> but was:<Error en caso de datos incorrectos!>
at test.TestAutomation.Login_Correcto(TestAutomation.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login_Correcto -->
  <testcase classname="test.TestAutomation" name="MessageError" time="2.151"/>
  <testcase classname="test.TestAutomation" name="MessageError" time="2.248">
    <failure type="java.lang.AssertionError" message="Error en caso de mail correcto! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error en caso de mail correcto! expected [true] but found [false]
at test.TestAutomation.MessageError(TestAutomation.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MessageError -->
  <testcase classname="test.TestAutomation" name="MessageError" time="2.527"/>
  <testcase classname="test.TestAutomation" name="create_Account" time="12.636"/>
  <testcase classname="test.TestAutomation" name="create_Account" time="15.98"/>
  <testcase classname="test.TestAutomation" name="create_Account" time="11.532"/>
</testsuite> <!-- Test -->
